### ISSUE TITLE
Problem with Dispersion and Droplet_distribution

### ISSUE THREAD

**Issue by HanhHelen** [NOAA-ORR-ERD/OilLibrary#14]
Dear authors,
When testing the oillibrary, i have the problems:
FAIL: test_dispersion (__main__.TestOil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/opendrift-master/tests/test_oillibrary.py", line 92, in test_dispersion
    fraction_dispersed)
AssertionError: 0.09339651 != 0.068167008 within 7 places

======================================================================
FAIL: test_droplet_distribution (__main__.TestOil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/opendrift-master/tests/test_oillibrary.py", line 130, in test_droplet_distribution
    self.assertAlmostEqual(d.mean(), 0.00006904389)
AssertionError: 5.763371939835245e-05 != 6.904389e-05 within 7 places

Would you please to help me?

**Comment by ChrisBarker-NOAA** [comment]
This looks like an open_drift test failure -- you'll need to ask its developers.

-CHB

**Comment by HanhHelen** [comment]
I got it. Thanks for anyway.
