### ISSUE TITLE
Technical documentation required

### ISSUE THREAD

**Issue by amirheidari** [NOAA-ORR-ERD/OilLibrary#16]
Dear Sir/ Madam,
I need the technical documentation of ADIOS oil library. I want to know what mathematical equations are used for modeling weathering processes in ADIOS. In the "Help" tab of ADIOS software, there are some information, but the equations are completely illegible. Would you please guide me where I can find the required information?

Best Regards
Payam Amir-Heidari
Sharif University of Technology

**Comment by ChrisBarker-NOAA** [comment]
This gitHub project is for NOAA's current oil libary project, not the ADIOS software.

However, we have answered your question in response to another email.

for future reference, the algorithms in ADIOS2 are documented in:

```
@article{LehrEtAl:2002,
author       ={William Lehr and Robert Jones and Mary Evans and Debra Simecek-Beatty and Roy Overstreet},
year         =2002,
title        ={Revisions of the ADIOS oil spill model},
journal      ={Environmental Modelling {\&} Software},
volume       = 17,
pages        = {191-199}
}
```

Closing this issue.
