### ISSUE TITLE
Problem with setup.py

### ISSUE THREAD

**Issue by vic1309** [NOAA-ORR-ERD/OilLibrary#17]
I have been trying to install OilLibrary as follows:

    $ git clone https://github.com/NOAA-ORR-ERD/OilLibrary.git
    $ cd OilLibrary/
    $ conda install -n victor --file conda_requirements.txt
    $ python setup.py develop

Where *victor* is my conda virtual environment. Opendrift is also located in there.

However, when I reach the last command, the following error message appears:

```
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    last_update = repo.iter_commits().next().committed_datetime.isoformat()
AttributeError: 'generator' object has no attribute 'next'
```
Any idea how to solve it?

Extra info:
Ubuntu 18.04.2 LTS, x86_64
Python: version 2.7

Cheers,
Victor

**Comment by ChrisBarker-NOAA** [comment]
You've closed this, so I'm guessing it was solved --were you running py3?

**Comment by vic1309** [comment]
Dear Chris Barker,

It was simpler than that! I cloned OilLibrary to my virtual environment but I was trying to setup it logged in my root. I just activated my environment and then it worked properly.
