### ISSUE TITLE
Help emuls_constant_min

### ISSUE THREAD

**Issue by Lemcastroro** [NOAA-ORR-ERD/OilLibrary#19]
Hi,
I am new to this and I am learning on my own.
I would like to know what the command is to obtain the **emuls_constant_min** and **water_content_emulsion** constants. Because these are not defined in oil and do not work with get_oil ()

I would also appreciate if there is any more detailed manual or any recommendation to learn how to handle this database correctly.

Thanks

Leidy

**Comment by ChrisBarker-NOAA** [comment]
Was this question ever addressed?

I don't want to close the issue if not.
