### ISSUE TITLE
Install Outside of git

### ISSUE THREAD

**Issue by Mandy1609** [NOAA-ORR-ERD/OilLibrary#21]
Hi,

I downloaded and installed the conda_requirements of the OilLibrary 1.1.1 version. I am trying to install outside of git, but when I run 'python setup.py install' I get the attached error. What am I missing?

![image](https://user-images.githubusercontent.com/69759387/91155523-08019c80-e6d4-11ea-8de7-bd67c50dde8b.png)

**Comment by ChrisBarker-NOAA** [comment]
Sorry about that -- it's using git to set a version number while under development. It should have a fallback for the "normal" case :-(

hang on, I'll see what I can do.

**Comment by ChrisBarker-NOAA** [comment]
OK -- should be fixed -- it will fail gracefully if you don't have gitpython or git itself installed.

Latest master or develop should work: v1.1.3
