### ISSUE TITLE
12 errors during collection

### ISSUE THREAD

**Issue by egiraldof** [NOAA-ORR-ERD/OilLibrary#24]
Hello

When I run the py.test I get a lot of errors like the ones shown in the following images: 

![Captura de pantalla de 2020-11-23 17-56-40](https://user-images.githubusercontent.com/64181788/100025361-9f9b8780-2db6-11eb-8dd2-956f118ed5bb.png)

![Captura de pantalla de 2020-11-23 17-57-26](https://user-images.githubusercontent.com/64181788/100025388-a7f3c280-2db6-11eb-9154-d1343aacbde1.png)

I don't know how to solve them, I would appreciate the help.

Bye.

**Comment by ChrisBarker-NOAA** [comment]
which version of the code did you download and build?

what platform are you on?

did the build process work without errors?

**Comment by ChrisBarker-NOAA** [comment]
and which version of Python?

**Comment by ChrisBarker-NOAA** [comment]
NOTE: I just tested the source code from gitHub and it all went well.

I suspect your install may have had an issue.

**Comment by egiraldof** [comment]
Thank you @ChrisBarker-NOAA , I was able to solve the problem a bit.

Apparently there was a conflict over the versions of zope.sqlalchemy and SQLAlchemy. I installed other versions different from the ones that appear in the conda_requirements.txt (By the way, the .txt file that I downloaded when I cloned the repository had these commented lines).

Now I only have two errors:

![Captura de pantalla de 2020-11-23 19-34-48](https://user-images.githubusercontent.com/64181788/100031212-09219300-2dc3-11eb-95ea-06edda503a9d.png)

**Comment by ChrisBarker-NOAA** [comment]
do check the rest of the dependencies -- if we've pinned a version, it does matter.

Also, it shouldn't matter, but try running the tests like so:

pytest --pyargs oil_library

that will run the installed version of the tests -- shouldn't make a difference, but you never know.

**Comment by ChrisBarker-NOAA** [comment]
Closing -- please reopen if you're still having trouble.

Note: #30 may be relevent.
