### ISSUE TITLE
problems with vapor_pressure method

### ISSUE THREAD

**Issue by lindbergh153** [NOAA-ORR-ERD/OilLibrary#34]
Hello developers,
I successfully installed the oil library package by conda with Python 3.8, but still unable to call vapor_pressure method. The misinformation is attached below.

Traceback (most recent call last):
  File "D:/PyOilSpill/test.py", line 160, in <module>
    print(gnome_oil.vapor_pressure(289))
TypeError: unhashable type: 'OilProps

[DB_build_Log.txt](https://github.com/NOAA-ORR-ERD/OilLibrary/files/7606476/DB_build_Log.txt)
'

**Comment by lindbergh153** [comment]
BTW, I can only run it in Py2.7 but failed in other versions like 3.76 and 3.8

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the bug report -- I was able to confirm the issue, and I've fixed it. 

I also added a test to for it.

I'm still very confused as to how we missed this, but here it is.

**Comment by ChrisBarker-NOAA** [comment]
It should be fixed in the latest release:

https://github.com/NOAA-ORR-ERD/OilLibrary/releases/tag/v2.0.1

(and master and develop branches)

**Comment by lindbergh153** [comment]
Dear Dr. Barker,It works finally! Thanks so much for your kind help. Best regardsZhaoyang Yang 发件人: Chris Barker发送时间: November 30, 2021 12:56 AM收件人: NOAA-ORR-ERD/OilLibrary抄送: lindbergh153; Author主题: Re: [NOAA-ORR-ERD/OilLibrary] problems with vapor_pressure method (Issue #34) Thanks for the bug report -- I was able to confirm the issue, and I've fixed it.I also added a test to for it.I'm still very confused as to how we missed this, but here it is.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChrisBarker-NOAA** [comment]
BTW: I thought I'd made this clear earlier, but in case I didn't:

This OilLibrary Package is not longer under development. If a simple bug like this one crops up, we'll try to fix it, but it won't see any further development.

Our development efforts are now focused on a new system -- in teh end, similar functionality,b ut new structure.

The data itself is available via an online database:

https://adios.orr.noaa.gov/oils

(note: we will be publishing the raw data, in JSON format on gitHub soon)

The code to process the data is in the adios_db package in the adios_oil_database project:

https://github.com/NOAA-ORR-ERD/adios_oil_database

And some of the computation specific to the oil weathering in now in PyGNOME:

https://github.com/NOAA-ORR-ERD/PyGnome

If you need oil-processing functionality outside of PyGNOME, let us know, we may be able to move some code around.
