### ISSUE TITLE
About miss NOAA database

### ISSUE THREAD

**Issue by ZenKa24** [NOAA-ORR-ERD/OilLibrary#4]
Dear authors,
I have installed OilLibrary for my Oil model which I am using. However, when I ran oil model I got this error:
ValueError: Oil type "ARABIAN MEDIUM, API" not found in NOAA database

Would you please help me fix this error? Or If I want to reinstall OilLibrary what I should do that?
I install it on ubuntu 12.04 (64bit).

Thanks and best regards,
Khanh Ngoc

**Comment by ChrisBarker-NOAA** [comment]
I _think_ this has been resolved -- but please re-open if it's still an issue.
